### ISSUE TITLE
Want to post a jar file to a release on GitHub by Gradle.

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/inspectus4katalon-gradle-plugin#66]
I asked GitHub Copilot:

>I want to programatically post a jar to a release using Gradle. How can I do it?

The following is the answere by Copilot:

----

You can use Gradle to programmatically publish a JAR file to a release on GitHub by configuring a workflow that triggers on the release event. Here's how you can set it up:

## 1. Configure your build.gradle file: 

Add the maven-publish plugin and configure the publishing block to point to GitHub Packages. Use the GITHUB_ACTOR and GITHUB_TOKEN environment variables for authentication.

Example configuration:

```
plugins {
    id 'maven-publish'
}
publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/OWNER/REPOSITORY")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
    publications {
        mavenJava(MavenPublication) {
            from(components.java)
        }
    }
}
```

Replace OWNER with your GitHub username or organization name and REPOSITORY with the name of your repository.

## 2. Create a GitHub Actions workflow: 

Define a workflow file (e.g., .github/workflows/publish.yml) to automate the process. This workflow will trigger on the release event and publish the JAR file using Gradle.

Example workflow:

```
name: Publish JAR to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Publish JAR
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This workflow performs the following steps:

1. Checks out the repository.
2. Sets up the Java JDK.
3. Sets up the Gradle environment.
4. Executes the publish task to upload the JAR file to GitHub Packages.

## 3. Set up secrets: 

Ensure that the GITHUB_TOKEN secret is available in your repository. GitHub automatically provides this token for workflows, and it is used for authentication.

Once configured, the workflow will automatically publish the JAR file to GitHub Packages whenever a new release is created. For more details, see [Publishing packages to GitHub Packages](https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-java-packages-with-gradle#publishing-packages-to-github-packages).
