### ISSUE TITLE
Should perform Continuous Integration (automated test execution for pull-requests) using GitHub Actions

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/inspectus4katalon-gradle-plugin#8]
derived from #6 

I want to automatical execute test for the pull requests to the master branch of the inspectus4katalon-gradle-plugin.

I want to write tests in JUnit5.

I want to execute CI using GitHub Actions.

I want the CI automated tests should record the status so that the issue #7 is resolved.

**Comment by kazurayam** [comment]
To start with, I will read the following article:

https://dev.to/ewefie/getting-started-with-github-actions-run-junit-5-tests-in-a-java-project-with-maven-20g4

**Comment by kazurayam** [comment]
I created the `develop` branch, which contains the version 0.1.5

```
$ git branch
* master
:~/github/inspectus4katalon-gradle-plugin (master)
$ git branch develop
:~/github/inspectus4katalon-gradle-plugin (master)
$ git checkout develop
Switched to branch 'develop'
:~/github/inspectus4katalon-gradle-plugin (develop)
$ git tag
0.1.1
0.1.2
0.1.4
0.1.5
```

In the develop branch, I changed the build.gradle to have 
```
version = "0.2.0-SNAPSHOT"
```

**Comment by kazurayam** [comment]
I installed a plugin "GitHub Actions" into IntelliJ IDEA.
I installed a plugin "GitHub Actions" into VSCODE.

**Comment by kazurayam** [comment]
at 0.1.5, I created `.github/workflows/tests.yml`

```
name: tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
  pull_request_review:
    branches:
      - master
jobs:
  # refer to https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
  run_junit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2
          arguments: :development:build

      - name: Run the Gradle test task
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: :development:test --tests "*"


```

See [GitHub Actions doc/ Building and testing Java with Gradle](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle)
